---
- name: Create Red Hat OpenShift AI namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    state: present
    definition: "{{ lookup('template', 'rhods_operator_namespace.yaml.j2') | from_yaml }}"
    wait_sleep: 10
    wait_timeout: 360

- name: Create Red Hat OpenShift AI OperatorGroup
  kubernetes.core.k8s:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    state: present
    definition: "{{ lookup('template', 'rhods_operator_operatorgroup.yaml.j2') | from_yaml }}"
    wait_sleep: 10
    wait_timeout: 360

- name: Create Red Hat OpenShift AI Operator Subscription
  kubernetes.core.k8s:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    state: present
    definition: "{{ lookup('template', 'rhods_operator_subscription.yaml.j2') | from_yaml }}"
    wait_sleep: 10
    wait_timeout: 360

- name: Wait for Data Science Cluster CRD
  kubernetes.core.k8s_info:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    kind: CustomResourceDefinition
    api_version: apiextensions.k8s.io/v1
    name: datascienceclusters.datasciencecluster.opendatahub.io
  register: rhods_dsc_crd
  until: 
    - rhods_dsc_crd.resources | length > 0
  retries: 60
  delay: 10

- name: Create Data Science Cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    state: present
    definition: "{{ lookup('template', 'datascience_cluster.yaml.j2') | from_yaml }}"
    wait_sleep: 10
    wait_timeout: 360

- name: "Wait for Data Science Cluster Readiness"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ install_dir }}/auth/kubeconfig"
    host: "https://api.{{ cluster_name }}.{{ sanitized_base_domain }}:6443"
    kind: DataScienceCluster
    api_version: datasciencecluster.opendatahub.io/v1
    name: "default-dsc"
  register: cluster_policy_status
  until: cluster_policy_status.resources | json_query('[*].status.conditions[?type==`Available`].status') | flatten | first | bool
  retries: 60
  delay: 10

